---
title: "Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(pmkl)
library(doParallel)
```


Simulation settings.
```{r}
ss1 <- expand.grid(sigma = 1:3,
                   ni = c(50, 100),
                   Ng = c("50:50:50", "40:50:60"),
                   sp = c("regular", "partially random", "totally random"),
                   KEEP.OUT.ATTRS = FALSE)
ss1$set <- 1:nrow(ss1)
ss1 <- ss1[, ncol(ss1):1]
ss1
```

In this document, we will only demonstrate the first setting.
```{r,eval=FALSE}
RData <- "sim_res.RData"
if(file.exists(RData)){
  load(RData)
}else{
  n_core <- detectCores() - 1
  cl <- makeCluster(n_core)
  registerDoParallel(cl)
  set.seed(808)
    sim_res <- tryCatch({
      foreach(sim = 1:500,
              .combine = rbind) %dopar%
        iteration()
    },error = function(e){
      return(list(fail = TRUE, e = e))
    })
  stopCluster(cl)
  save(list = "sim_res", file = RData)
}
```

```{r}
data("sim_res")
pmkl:::tab.pii(1)
pmkl:::tab.rival(1)
```
